backend:
  ~needs: [build-backend, pg]
  volumes:
    - name: uploads
      emptyDir: {}
  volumeMounts:
    - mountPath: /app/public/uploads
      name: uploads
  envFrom:
    - secretRef:
        name: "pg-app"
    - secretRef:
        name: backend-sealed-secret
    - configMapRef:
        name: backend-configmap

jobs:
  runs:
    build-frontend-guyane:
      with:
        buildArgs:
          buildenv: dev.guyane

    build-frontend-aime:
      with:
        buildArgs:
          buildenv: dev.aime
