kind: ConfigMap
apiVersion: v1
metadata:
  name: backend-configmap
data:
  CRON_ENABLE: "false"
  URL: "https://backend-tumeplay-preprod.dev.fabrique.social.gouv.fr"
  DOMAIN_API: "https://backend-tumeplay-preprod.dev.fabrique.social.gouv.fr/"
  EMAIL_PROVIDER_HOST: "pro2.mail.ovh.net"
  EMAIL_PROVIDER_PORT: "587"
  EMAIL_PROVIDER_SECURE: "false"
  EMAIL_PROVIDER_USERNAME: "info.tumeplay@fabrique.social.gouv.fr"
  EMAIL_PROVIDER_TLS: "false"
  EMAIL_PROVIDER_FROM: "Tumeplay <info.tumeplay@fabrique.social.gouv.fr>"
  EMAIL_PROVIDER_REPLY_TO: "info.tumeplay@fabrique.social.gouv.fr"
  EMAIL_CONFIG_ADMIN: "clement@numericite.eu"
  EMAIL_CONFIG_CAT: "maxime.lecoq@benextcompany.com"
