backend:
  host: backend-tumeplay.fabrique.social.gouv.fr
  envFrom:
    - secretRef:
        name: pg-user # temporary
    - secretRef:
        name: backend-sealed-secret
    - configMapRef:
        name: backend-configmap
    - secretRef:
        name: azure-tumeplay-volume

frontend-metropole:
  host: tumeplay.fabrique.social.gouv.fr
  redirectFrom:
    - metropole-tumeplay.fabrique.social.gouv.fr

frontend-guyane:
  host: guyane-tumeplay.fabrique.social.gouv.fr
  redirectFrom:
    - guyane.tumeplay.fabrique.social.gouv.fr

frontend-aime:
  host: aime-tumeplay.fabrique.social.gouv.fr
  redirectFrom:
    - aime.tumeplay.fabrique.social.gouv.fr

dashboard:
  host: bo-tumeplay.fabrique.social.gouv.fr

pg-metabase:
  ~chart: pg

metabase:
  enabled: true
  ~needs: ["pg-metabase"]
  # ingress:
  #   enabled: false
  envFrom:
    - secretRef:
        name: pg-metabase-app
    - configMapRef:
        name: metabase-configmap

jobs:
  runs:
    build-frontend-guyane:
      with:
        buildArgs:
          buildenv: preprod.guyane
          REACT_APP_MATOMO_ID: "45"

    build-frontend-aime:
      with:
        buildArgs:
          buildenv: preprod.aime
