backend:
  host: backend-tumeplay.fabrique.social.gouv.fr
  envFrom:
    - secretRef:
        name: pg-app
    - secretRef:
        name: backend-sealed-secret
    - configMapRef:
        name: backend-configmap
    - secretRef:
        name: azure-tumeplay-volume

frontend-metropole:
  host: tumeplay.fabrique.social.gouv.fr
  redirectFrom:
    - metropole-tumeplay.fabrique.social.gouv.fr

frontend-guyane:
  host: guyane-tumeplay.fabrique.social.gouv.fr
  redirectFrom:
    - guyane.tumeplay.fabrique.social.gouv.fr

frontend-aime:
  host: aime-tumeplay.fabrique.social.gouv.fr
  redirectFrom:
    - aime.tumeplay.fabrique.social.gouv.fr

dashboard:
  host: bo-tumeplay.fabrique.social.gouv.fr

pg:
  cnpg-cluster:
    resources:
      requests:
        memory: 128Mi
      limits:
        memory: 1Gi

pg-metabase:
  ~chart: pg
  cnpg-cluster:
    resources:
      requests:
        memory: 128Mi
      limits:
        memory: 1Gi

metabase:
  enabled: true
  ~chart: metabase
  ~needs: ["pg-metabase"]
  # ingress:
  #   enabled: false
  envFrom:
    - secretRef:
        name: pg-metabase-app
    - secretRef:
        name: metabase-secret
  env:
    - name: MB_DB_CONNECTION_URI
      value: "$(DATABASE_URL)"
    - name: MB_APPLICATION_NAME
      value: metabase-TuMePlay

  #     - secretKeyRef:
  #         name: pg-metabase-app
  #         key: DATABASE_URL
  #postgresql://${PG_HOST}/metabase?user=xxx&password=yyy&ssl=require"

jobs:
  runs:
    build-frontend-guyane:
      with:
        buildArgs:
          buildenv: preprod.guyane
          REACT_APP_MATOMO_ID: "45"

    build-frontend-aime:
      with:
        buildArgs:
          buildenv: preprod.aime
