backend:
  host: backend-tumeplay.fabrique.social.gouv.fr
  envFrom:
    - secretRef:
        name: pg-app
    - secretRef:
        name: backend-sealed-secret
    - configMapRef:
        name: backend-configmap
    # - secretRef:
    #     name: azure-tumeplay-volume

frontend-metropole:
  host: tumeplay.fabrique.social.gouv.fr
  redirectFrom:
    - metropole-tumeplay.fabrique.social.gouv.fr

frontend-guyane:
  host: guyane-tumeplay.fabrique.social.gouv.fr
  redirectFrom:
    - guyane.tumeplay.fabrique.social.gouv.fr

frontend-aime:
  host: aime-tumeplay.fabrique.social.gouv.fr
  redirectFrom:
    - aime.tumeplay.fabrique.social.gouv.fr

dashboard:
  host: bo-tumeplay.fabrique.social.gouv.fr

pg:
  backup:
    name: ovh # backup on a new folder
  cnpg-cluster:
    recovery:
      enabled: true
      ~tpl~database: "{{ .Values.global.pgDatabase }}"
      ~tpl~owner: "{{ .Values.global.pgUser }}"
      secretName: "pg-db"
      barmanObjectStore:
        ~tpl~destinationPath: "s3://tumeplay-prod-backups/tumeplay"
        s3Credentials:
          accessKeyId:
            ~tpl~name: "tumeplay-prod-backups-access-key"
            key: bucket_access_key
          secretAccessKey:
            ~tpl~name: "tumeplay-prod-backups-access-key"
            key: bucket_secret_key
          region:
            ~tpl~name: "tumeplay-prod-backups-access-key"
            key: bucket_region
    resources:
      requests:
        memory: 128Mi
      limits:
        memory: 1Gi

jobs:
  runs:
    build-frontend-guyane:
      with:
        buildArgs:
          buildenv: preprod.guyane
          REACT_APP_MATOMO_ID: "45"

    build-frontend-aime:
      with:
        buildArgs:
          buildenv: preprod.aime
