backend:
  host: backend-tumeplay.fabrique.social.gouv.fr

frontend-metropole:
  host: tumeplay.fabrique.social.gouv.fr
  redirectFrom:
    - metropole-tumeplay.fabrique.social.gouv.fr

frontend-guyane:
  host: guyane-tumeplay.fabrique.social.gouv.fr
  redirectFrom:
    - guyane.tumeplay.fabrique.social.gouv.fr

frontend-aime:
  host: aime-tumeplay.fabrique.social.gouv.fr
  redirectFrom:
    - aime.tumeplay.fabrique.social.gouv.fr

dashboard:
  host: bo-tumeplay.fabrique.social.gouv.fr

metabase:
  enabled: true
  # ingress:
  #   enabled: false
  envFrom:
    - secretRef:
        name: metabase-pg-user
    - configMapRef:
        name: metabase-configmap

jobs:
  runs:
    build-frontend-guyane:
      with:
        buildArgs:
          buildenv: preprod.guyane
          REACT_APP_MATOMO_ID: "45"
          
    build-frontend-aime:
      with:
        buildArgs:
          buildenv: preprod.aime
          