app-backend:
  host: backend-tumeplay.fabrique.social.gouv.fr
  certSecretName: backend-crt

app-frontend-metropole:
  host: tumeplay.fabrique.social.gouv.fr
  certSecretName: metropole-crt
  redirectFrom:
    - metropole-tumeplay.fabrique.social.gouv.fr
  env:
    - name: MATOMO_URL
      value: https://matomo.fabrique.social.gouv.fr/
    - name: MATOMO_SITE_ID
      value: "77"

app-frontend-guyane:
  host: guyane-tumeplay.fabrique.social.gouv.fr
  certSecretName: guyane-crt
  redirectFrom:
    - guyane.tumeplay.fabrique.social.gouv.fr

app-dashboard:
  host: bo-tumeplay.fabrique.social.gouv.fr
  certSecretName: dashboard-crt

metabase:
  enabled: true
  # ingress:
  #   enabled: false
  envFrom:
    - secretRef:
        name: metabase-pg-user
    - configMapRef:
        name: metabase-configmap
