app-backend:
  needs: [db]
  envFrom:
    - secretRef:
        name: pg-user-{{ .Values.global.branchSlug }}
    - secretRef:
        name: carnets-sealed-secret
    - configMapRef:
        name: carnets-configmap

jobs:
  enabled: true
  runs:
    - name: db
      use: SocialGouv/kube-workflow/jobs/create-db
      with:
        pgAdminSecretRefName: azure-pg-admin-user
