app-backend:
  enabled: true
  imagePackage: backend
  probesPath: /_health
  envFrom:
    - secretRef:
        name: pg-user
    - secretRef:
        name: backend-sealed-secret
    - configMapRef:
        name: backend-configmap

app-frontend-metropole:
  enabled: false

app-frontend-guyane:
  enabled: false

app-dashboard:
  enabled: false