name: Preproduction

on:
  push:
    branches: [main, alpha, beta, next]

concurrency:
  group: preproduction
  cancel-in-progress: true

jobs:
  register-backend:
    name: Build & Register application
    runs-on: ubuntu-latest
    steps:
      - name: Use autodevops build and register
        uses: SocialGouv/actions/autodevops-build-register@v1
        with:
          environment: preprod
          imagePackage: backend
          dockercontext: ./back-strapi
          dockerfile: ./back-strapi/Dockerfile
          token: ${{ secrets.GITHUB_TOKEN }}

  register-frontend-guyane:
    name: Register frontend Guyane
    runs-on: ubuntu-latest
    steps:
      - name: Use autodevops build and register
        uses: SocialGouv/actions/autodevops-build-register@v1
        with:
          environment: preprod
          imagePackage: frontend-guyane
          dockercontext: ./tumeplay-app
          dockerfile: ./tumeplay-app/Dockerfile
          token: ${{ secrets.GITHUB_TOKEN }}
          dockerbuildargs: |
            buildenv=preprod.guyane
            REACT_APP_MATOMO_ID=49
            REACT_APP_ZONE=guyane
            REACT_APP_API_URL=https://backend-tumeplay-preprod.dev.fabrique.social.gouv.fr
            REACT_APP_OTHER_ZONE_URL=https://tumeplay-preprod.dev.fabrique.social.gouv.fr

  register-frontend-metropole:
    name: Register frontend Metropole
    runs-on: ubuntu-latest
    steps:
      - name: Use autodevops build and register
        uses: SocialGouv/actions/autodevops-build-register@v1
        with:
          environment: preprod
          imagePackage: frontend-metropole
          dockercontext: ./tumeplay-vitrine
          dockerfile: ./tumeplay-vitrine/Dockerfile
          token: ${{ secrets.GITHUB_TOKEN }}
          dockerbuildargs: |
            NEXT_PUBLIC_STRAPI_URL=https://backend-${{ env.host }}.dev.fabrique.social.gouv.fr

  register-dashboard:
    name: Register dashboard
    runs-on: ubuntu-latest
    steps:
      - name: Use autodevops build and register
        uses: SocialGouv/actions/autodevops-build-register@v1
        with:
          environment: preprod
          imagePackage: dashboard
          dockercontext: ./tumeplay-dashboard
          dockerfile: ./tumeplay-dashboard/Dockerfile
          token: ${{ secrets.GITHUB_TOKEN }}
          dockerbuildargs: |
            REACT_APP_API_URL=https://backend-tumeplay-preprod.dev.fabrique.social.gouv.fr

  deploy:
    name: Deploy preproduction
    runs-on: ubuntu-latest
    needs:
      [
        register-backend,
        register-dashboard,
        register-frontend-guyane,
        register-frontend-metropole,
      ]
    environment:
      name: preproduction
      url: https://bo-tumeplay-preprod.dev.fabrique.social.gouv.fr
    steps:
      - name: Use autodevops deployment
        uses: SocialGouv/kube-workflow@v1
        with:
          environment: preprod
          token: ${{ secrets.GITHUB_TOKEN }}
          kubeconfig: ${{ secrets.KUBECONFIG }}
          rancherProjectId: ${{ secrets.RANCHER_PROJECT_ID }}
          rancherProjectName: ${{ secrets.RANCHER_PROJECT_NAME }}
