name: publish-tumeplay-images
on:
  release:
    types: [published]
jobs:
  push_to_registry:
    name: Push Docker images to GitHub Packages
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Lowercase repo and tag
        run: |
          echo IMAGE_REPOSITORY=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]') >> $GITHUB_ENV
          echo IMAGE_TAG=$(echo ${{ github.ref }} | tr '[:upper:]' '[:lower:]' | awk '{split($0,a,"/"); print a[3]}') >> $GITHUB_ENV
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build strapi image
        uses: docker/build-push-action@v2
        with:
          context: ./back-strapi
          push: true
          tags: |
            docker.pkg.github.com/${{ env.IMAGE_REPOSITORY }}/tumeplay-strapi:${{ github.sha }}
            docker.pkg.github.com/${{ env.IMAGE_REPOSITORY }}/tumeplay-strapi:${{ env.IMAGE_TAG }}
      - name: Build app react image guyane
        uses: docker/build-push-action@v2
        with:
          context: ./tumeplay-app
          push: true
          build-args: buildenv=dev.guyane
          tags: |
            docker.pkg.github.com/${{ env.IMAGE_REPOSITORY }}/tumeplay-app-guyane:${{ github.sha }}
            docker.pkg.github.com/${{ env.IMAGE_REPOSITORY }}/tumeplay-app-guyane:${{ env.IMAGE_TAG }}
      - name: Build app react image aime
        uses: docker/build-push-action@v2
        with:
          context: ./tumeplay-app
          push: true
          build-args: buildenv=dev.aime
          tags: |
            docker.pkg.github.com/${{ env.IMAGE_REPOSITORY }}/tumeplay-app-aime:${{ github.sha }}
            docker.pkg.github.com/${{ env.IMAGE_REPOSITORY }}/tumeplay-app-aime:${{ env.IMAGE_TAG }}
      - name: Build app react image metropole
        uses: docker/build-push-action@v2
        with:
          context: ./tumeplay-app
          push: true
          build-args: buildenv=dev.metropole
          tags: |
            docker.pkg.github.com/${{ env.IMAGE_REPOSITORY }}/tumeplay-app-metropole:${{ github.sha }}
            docker.pkg.github.com/${{ env.IMAGE_REPOSITORY }}/tumeplay-app-metropole:${{ env.IMAGE_TAG }}
