name: Review

on:
  push:
    branches-ignore: 
      - main
    tags-ignore:
      - v*

concurrency:
  cancel-in-progress: true
  group: review-${{ github.ref }}

jobs:
  register-backend:
    name: Build & Register application
    runs-on: ubuntu-latest
    steps:
    - name: Use autodevops build and register
      uses: SocialGouv/actions/autodevops-build-register@v1
      with:
        environment: dev
        imagePackage: backend
        dockercontext: ./back-strapi
        dockerfile: ./back-strapi/Dockerfile
        token: ${{ secrets.GITHUB_TOKEN }}

  register-frontend-guyane:
    name: Register frontend Guyane
    runs-on: ubuntu-latest
    steps:
    - name: Use autodevops build and register
      uses: SocialGouv/actions/autodevops-build-register@v1
      with:
        environment: dev
        imagePackage: frontend-guyane
        dockercontext: ./tumeplay-app
        dockerfile: ./tumeplay-app/Dockerfile
        token: ${{ secrets.GITHUB_TOKEN }}
        dockerbuildargs: |
          buildenv=dev.guyane
          REACT_APP_API_URL=%%REACT_APP_API_URL%%
          REACT_APP_ZONE=%%REACT_APP_ZONE%%
          REACT_APP_OTHER_ZONE_URL=%%REACT_APP_OTHER_ZONE_URL%%

  register-frontend-metropole:
    name: Register frontend Metropole
    runs-on: ubuntu-latest
    steps:
    - name: Use autodevops build and register
      uses: SocialGouv/actions/autodevops-build-register@v1
      with:
        environment: dev
        imagePackage: frontend-metropole
        dockercontext: ./tumeplay-app
        dockerfile: ./tumeplay-app/Dockerfile
        token: ${{ secrets.GITHUB_TOKEN }}
        dockerbuildargs: |
          buildenv=dev.metropole
          REACT_APP_API_URL=%%REACT_APP_API_URL%%
          REACT_APP_ZONE=%%REACT_APP_ZONE%%
          REACT_APP_OTHER_ZONE_URL=%%REACT_APP_OTHER_ZONE_URL%%

  register-dashboard:
    name: Register dashboard
    runs-on: ubuntu-latest
    steps:
    - name: Use autodevops build and register
      uses: SocialGouv/actions/autodevops-build-register@v1
      with:
        environment: dev
        imagePackage: dashboard
        dockercontext: ./tumeplay-dashboard
        dockerfile: ./tumeplay-dashboard/Dockerfile
        token: ${{ secrets.GITHUB_TOKEN }}
        dockerbuildargs: |
          REACT_APP_API_URL=%%REACT_APP_API_URL%%

  deploy:
    name: Deploy review branch
    runs-on: ubuntu-latest
    needs:
      [
        register-backend,
        register-dashboard,
        register-frontend-guyane,
        register-frontend-metropole,
      ]
    steps:
    - name: Use kube-workflow deployment
      uses: SocialGouv/kube-workflow@v1
      with:
        environment: dev
        token: ${{ secrets.GITHUB_TOKEN }}
        kubeconfig: ${{ secrets.KUBECONFIG }}
        rancherProjectId: ${{ secrets.RANCHER_PROJECT_ID }}
        rancherProjectName: ${{ secrets.RANCHER_PROJECT_NAME }}
