name: Review

on:
  push:
    branches:
      - "**"
    tags-ignore:
      - v*

concurrency:
  cancel-in-progress: true
  group: review-${{ github.ref }}

jobs:
  ##############################################################################
  ## BUILD AND REGISTER BACKEND IMAGE
  ##############################################################################
  register-backend:
    name: Build & Register application
    runs-on: ubuntu-latest
    steps:

    - name: Get project name
      run: |
        echo "project=${GITHUB_REPOSITORY#*/}" >> $GITHUB_ENV

    - name: Use autodevops build and register
      uses: SocialGouv/actions/autodevops-build-register@local-cache
      with:
        imageName: ${{ env.project }}/backend
        dockercontext: ./back-strapi
        dockerfile: ./back-strapi/Dockerfile
        project: ${{ env.project }}
        token: ${{ secrets.GITHUB_TOKEN }}

  ##############################################################################
  ## BUILD AND REGISTER FRONTEND GUYANE
  ##############################################################################
  register-frontend-guyane:
    name: Register frontend Guyane
    runs-on: ubuntu-latest
    steps:

    - name: Get project name
      run: |
        echo "project=${GITHUB_REPOSITORY#*/}" >> $GITHUB_ENV

    - name: Use autodevops build and register
      uses: SocialGouv/actions/autodevops-build-register@local-cache
      with:
        imageName: ${{ env.project }}/frontend-guyane
        dockercontext: ./tumeplay-app
        dockerfile: ./tumeplay-app/Dockerfile
        project: ${{ env.project }}
        token: ${{ secrets.GITHUB_TOKEN }}
        dockerbuildargs: |
          buildenv=dev.guyane
          REACT_APP_API_URL=%%REACT_APP_API_URL%%
          REACT_APP_ZONE=%%REACT_APP_ZONE%%
          REACT_APP_OTHER_ZONE_URL=%%REACT_APP_OTHER_ZONE_URL%%

    - name: debug backend URL
      run: |
        echo https://backend-${{ env.project }}-${{ env.branch }}.${{ env.SOCIALGOUV_BASE_DOMAIN }}

  ##############################################################################
  ## BUILD AND REGISTER FRONTEND GUYANE
  ##############################################################################
  register-frontend-metropole:
    name: Register frontend Metropole
    runs-on: ubuntu-latest
    steps:

    - name: Get project name
      run: |
        echo "project=${GITHUB_REPOSITORY#*/}" >> $GITHUB_ENV

    - name: Use autodevops build and register
      uses: SocialGouv/actions/autodevops-build-register@local-cache
      with:
        imageName: ${{ env.project }}/frontend-metropole
        dockercontext: ./tumeplay-app
        dockerfile: ./tumeplay-app/Dockerfile
        project: ${{ env.project }}
        token: ${{ secrets.GITHUB_TOKEN }}
        dockerbuildargs: |
          buildenv=dev.metropole
          REACT_APP_API_URL=%%REACT_APP_API_URL%%
          REACT_APP_ZONE=%%REACT_APP_ZONE%%
          REACT_APP_OTHER_ZONE_URL=%%REACT_APP_OTHER_ZONE_URL%%

    - name: debug backend URL
      run: |
        echo https://backend-${{ env.project }}-${{ env.branch }}.${{ env.SOCIALGOUV_BASE_DOMAIN }}

  ##############################################################################
  ## BUILD AND REGISTER DASHBOARD
  ##############################################################################
  register-dashboard:
    name: Register dashboard
    runs-on: ubuntu-latest
    steps:

    - name: Get project name
      run: |
        echo "project=${GITHUB_REPOSITORY#*/}" >> $GITHUB_ENV

    - name: Use autodevops build and register
      uses: SocialGouv/actions/autodevops-build-register@local-cache
      with:
        imageName: ${{ env.project }}/dashboard
        dockercontext: ./tumeplay-dashboard
        dockerfile: ./tumeplay-dashboard/Dockerfile
        project: ${{ env.project }}
        token: ${{ secrets.GITHUB_TOKEN }}
        dockerbuildargs: |
          REACT_APP_API_URL=%%REACT_APP_API_URL%%

  ##############################################################################
  ## GENERATE KUBERNETES MANIFESTS
  ##############################################################################
  manifests:
    name: Generate k8s manifests
    runs-on: ubuntu-latest
    steps:

    - name: Use autodevops manifests generation
      uses: SocialGouv/actions/k8s-manifests@v1
      with:
        environment: "dev"

  ##############################################################################
  ## DEPLOY BACKEND & FRONT-END
  ##############################################################################
  deploy:
    name: Deploy review branch
    runs-on: ubuntu-latest
    needs:
      [
        manifests,
        register-backend,
        register-dashboard,
        register-frontend-guyane,
        register-frontend-metropole,
      ]
    steps:

    - name: Use autodevops deployment
      uses: SocialGouv/actions/autodevops-deploy@v1
      with:
        environment: "dev"
        token: ${{ secrets.GITHUB_TOKEN }}
        kubeconfig: ${{ secrets.SOCIALGOUV_KUBE_CONFIG_DEV2 }}
